# Generated by Django 4.0 on 2022-05-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(choices=[('FREE', 'FREE'), ('BASIC', 'BASIC'), ('PREMIUM', 'PREMIUM'), ('UNLIMITED', 'UNLIMITED')], max_length=250),
        ),
    ]
